### ISSUE TITLE
Getting non-fatal error on startup

### ISSUE THREAD

**Issue by ijre** [ForeverAndEverTeam/fae-mod#71] opened 2022-12-24 19:21 UTC
Hi, I'm submitting this on behalf of my friend, who doesn't have a GitHub account.  
He said he's okay with being messaged on Discord, at Zeli#2222  
  
On startup, he gets this error:  

<details>While running game code:
  File "game/core/expr.rpy", line 549, in _find_target_override
  File "game/core/expr.rpy", line 496, in _auto_gen
  File "game/core/expr.rpy", line 261, in fae_gen_sprite
AttributeError: 'NoneType' object has no attribute 'necklace'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/core/script-ch30.rpyc", line 402, in script call
  File "game/dialogs/script-greetings.rpyc", line 533, in script
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\character.py", line 1206, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\character.py", line 1030, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\character.py", line 986, in resolve_say_attributes
    renpy.exports.show(show_image)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "game/core/expr.rpy", line 549, in _find_target_override
  File "game/core/expr.rpy", line 496, in _auto_gen
  File "game/core/expr.rpy", line 261, in fae_gen_sprite
AttributeError: 'NoneType' object has no attribute 'necklace'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Forever & Ever 0.1.0
Sat Dec 24 20:07:47 2022</details>  
  
After spamming "Ignore" several times, he then got this error:  
<details>While running game code:
  File "game/core/script-ch30.rpy", line 358, in <module>
  File "game/core/utilities.rpy", line 463, in wait
AttributeError: 'NoneType' object has no attribute 'style'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/core/script-ch30.rpyc", line 358, in script
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/core/script-ch30.rpy", line 358, in <module>
  File "game/core/utilities.rpy", line 463, in wait
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\exports.py", line 1537, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\core.py", line 3912, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\core.py", line 2602, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 495, in renpy.display.render.render_screen
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\layout.py", line 884, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\layout.py", line 884, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\layout.py", line 884, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\transform.py", line 747, in render
    return transform_render(self, width, height, st, at)
  File "accelerator.pyx", line 187, in renpy.display.accelerator.transform_render
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\image.py", line 506, in render
    return wrap_render(self.target, width, height, st, at)
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\image.py", line 309, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\layout.py", line 371, in render
    surf = render(self.child, width, height, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "E:\DDLC - Forever & Ever New Beginnings\renpy\display\layout.py", line 1535, in render
    cr = renpy.display.render.render(self.child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 222, in renpy.display.render.render
AttributeError: 'NoneType' object has no attribute 'style'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Forever & Ever 0.1.0
Sat Dec 24 20:16:50 2022</details>

**Comment by TRIDENT1313** [comment] 2022-12-25 05:58
Hi!
Thanks for raising an issue!
After taking a look at the report, I believe I've figured out the cause.
It will be fixed for the upcoming hotfix update!

**Closed** 2022-12-25 21:08 UTC
Labels: bug
