### ISSUE TITLE
Sayori told me she messed with the code and suddenly all my compliments are gone

### ISSUE THREAD

**Issue by wowm03** [ForeverAndEverTeam/fae-mod#103] opened 2023-04-13 01:33 UTC
as stated in the title, everything was going fine until today when I open up the game and she told me she messed with the code and to restart. I did so and yet still, the compliments are left with loving her eyes, hair and that she's beautiful. I used to have compliments like "thanks for being here" and "you're so kind..." and such.

**Comment by TRIDENT1313** [comment] 2023-04-13 02:42
That's fine, that was by design.
There was a bug in affection that was hastily patched from it.
An update will be released in the near future which streamlines unlocks a bit more.

tl;dr don't worry about it.

**Closed by TRIDENT1313** 2023-04-13 02:42 UTC
